---
- hosts: all
  become: true
  vars:
      users:
         - toto
         - tata
         - titi
  tasks:
    - name: Creer un utilisateur
      user: 
         name: "{{item}}"
      with_items:
        "{{ users}}"
